package fp.persona;

public enum PosicionCampo {
	PORTERO, LIBERO, DEFENSA, LATERAL, PIVOTE, CENTROCAMPISTA, INTERIOR, VOLANTE,
	MEDIAPUNTA, ENGANCHE, SEGUNDODELANTERO, EXTERIOR, DELANTERO, ARIETE;
}
